# https://starship.rs/config/

add_newline = false

[character]
symbol = "âœ"

[package]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[git_branch]
style = "bold yellow"

[git_status]
conflicted = "ğŸ’¥"
ahead = "â¬†ï¸"
behind = "â¬‡ï¸"
diverged = "ğŸ”€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
untracked = "âœ¨"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 30
style = "bold red"

[line_break]
disabled = false

[cmd_duration]
disabled = true
